app/javascript/blacklight/layouts/showPage.vue
app/javascript/blacklight/result/item.vue
app/javascript/test/item.spec.js

See
https://github.com/sul-dlss-labs/rialto-derivatives/blob/feed4905093cf3a00cfa6895c50cc60517290ab0/transform/default_indexer.go#L15

Title field is title_tesi not _tsim

---

app/models/organization.rb
spec/requests/departments_spec.rb

Sort the department list by name

---

app/javascript/app.vue

Link analytics header to the homepage.

---

app/javascript/blacklight/facet/item.vue

Facets use the brown background

---

app/javascript/app.vue

Expand the logo so it always shows.

---

app/javascript/blacklight/layouts/reports.vue
app/javascript/blacklight/reports/table.vue
app/javascript/test/reports.spec.js
app/models/organization.rb

Display reports in an HTML table

---

app/controllers/catalog_controller.rb
app/javascript/blacklight/result/item.vue
app/javascript/test/item.spec.js
spec/fixtures/sample_solr_documents.yml

See https://github.com/sul-dlss-labs/rialto-derivatives/pull/75

Use a tokenized field for name

---

Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb

Update blacklight to show the Person show fields

---

app/controllers/catalog_controller.rb

Correct the `author_labels_tsim` field name

Organize fields for publications

---

Gemfile
Gemfile.lock
app/javascript/blacklight/layouts/showPage.vue

Display field labels on the show page

---

app/javascript/blacklight/searchControl.vue

Search when the form is submitted

---

app/javascript/blacklight/layouts/showPage.vue
app/javascript/blacklight/result/item.vue
app/javascript/blacklight/result/property_list.vue
app/javascript/blacklight/result/title.vue
app/javascript/test/title.spec.js

Fixes a bug where the show page was erroring because the document wasn't loaded.

Use the same Title component for index and show

---

.circleci/config.yml
.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb
app/models/solr_document.rb
spec/requests/catalog_spec.rb

when viewing publications, authors are connected to publications and are viewable/linked (from publications --> authors)

Link the author to the author show page

---

README.md
app/models/person.rb
app/services/authors_coauthors_report_generator.rb
spec/services/authors_coauthors_report_generator_spec.rb

references https://github.com/sul-dlss-labs/rialto-derivatives/issues/101

Makes person to org via position one-to-many.

---

Gemfile
Gemfile.lock

Update Blacklight to master

---

app/javascript/blacklight/layouts/showPage.vue
yarn.lock

Route to people.

---

app/controllers/catalog_controller.rb

Adds concepts facet.

---

app/javascript/blacklight/pagination.vue

Don't show NaN before results are fetched.

---

.rubocop.yml
.rubocop_todo.yml
app/models/organization.rb
app/models/person.rb
db/migrate/20181025210631_add_name_to_people.rb
db/migrate/20181025210730_add_name_to_organization.rb
db/schema.rb
spec/requests/departments_spec.rb
spec/services/authors_coauthors_report_generator_spec.rb
spec/services/choropleth_report_generator_spec.rb

Remove names from the json and make them a field.

---

app/controllers/catalog_controller.rb

Change facet from University to Institution

---

app/javascript/blacklight/facet/item.vue
app/javascript/blacklight/facet/value.vue
app/javascript/blacklight/layouts/search.vue
app/javascript/blacklight/pagination.vue
app/javascript/packs/blacklight_vue.js

Improve route setting based on state

---

app/controllers/catalog_controller.rb

Set higher limit values

---

app/controllers/catalog_controller.rb

closes https://github.com/sul-dlss-labs/rialto-derivatives/issues/130

Adds publication year facet and display for publications.

---

app/controllers/catalog_controller.rb

Move the school facet above the department facet

---

app/models/person.rb
app/services/authors_coauthors_report_generator.rb
spec/services/authors_coauthors_report_generator_spec.rb

closes https://github.com/sul-dlss-labs/rialto-webapp/issues/108

Fixes author coauthor report. Adds country facet to browse.

---

app/controllers/catalog_controller.rb

Adds facet for person subtypes.

---

app/controllers/catalog_controller.rb

Adds institute facet. Cleans up facet config.

---

app/controllers/reports_controller.rb
app/javascript/blacklight/layouts/collaboration_report.vue
app/javascript/blacklight/layouts/home.vue
app/javascript/packs/blacklight_vue.js
app/javascript/test/reports.spec.js
app/services/authors_coauthor_countries_report_generator.rb
app/services/authors_coauthor_institutions_report_generator.rb
spec/services/authors_coauthor_countries_report_generator_spec.rb
spec/services/authors_coauthor_institutions_report_generator_spec.rb

Adds country and institution coauthor reports.

---

app/services/authors_coauthor_countries_report_generator.rb
spec/services/authors_coauthor_countries_report_generator_spec.rb
spec/services/authors_coauthor_institutions_report_generator_spec.rb

Don't display multiple countries in coauthor country report. Tightened up report tests.

---

app/controllers/concepts_controller.rb
app/controllers/reports_controller.rb
app/javascript/blacklight/layouts/crossDisciplinaryReport.vue
app/javascript/blacklight/layouts/home.vue
app/javascript/packs/blacklight_vue.js
app/models/concept.rb
app/models/publication.rb
app/services/cross_disciplinary_report_generator.rb
app/views/concepts/index.json.jbuilder
config/routes.rb
db/migrate/20181031172550_create_concept.rb
db/schema.rb
spec/services/cross_disciplinary_report_generator_spec.rb

Initial cross-disciplinary research report with filtering by concept.

---

app/controllers/reports_controller.rb
app/controllers/schools_controller.rb
app/javascript/blacklight/choropleth.vue
app/javascript/blacklight/layouts/collaboration_report.vue
app/javascript/test/reports.spec.js
app/models/organization.rb
app/models/person.rb
app/services/authors_coauthor_countries_report_generator.rb
app/services/authors_coauthor_institutions_report_generator.rb
app/services/authors_coauthors_report_generator.rb
app/views/departments/index.json.jbuilder
app/views/schools/index.json.jbuilder
config/routes.rb
spec/requests/csv_reports_spec.rb
spec/services/authors_coauthor_countries_report_generator_spec.rb
spec/services/authors_coauthor_institutions_report_generator_spec.rb
spec/services/authors_coauthors_report_generator_spec.rb

Adds school filter to collaborator reports.

---

app/controllers/reports_controller.rb
app/javascript/blacklight/layouts/home.vue
app/javascript/blacklight/layouts/research_trends_report.vue
app/javascript/packs/blacklight_vue.js
app/services/research_trends_report_generator.rb
spec/services/research_trends_report_generator_spec.rb

Adds research trends by topic report.

---

app/javascript/blacklight/layouts/home.vue

Rejiggered reports on analytics home page.

---

app/javascript/blacklight/pagination.vue
app/javascript/test/pagination.spec.js
package.json
yarn.lock

Show a no results message when there are no results.

---

config/webpack/environment.js
package.json
yarn.lock

This resolves "No parser and no filepath given" errors when running
`./bin/webpack-dev-server`

Update vue-loader to v15

---

app/controllers/catalog_controller.rb

DOI should only show for publications

---

app/javascript/app.vue
app/javascript/blacklight/layouts/search.vue
app/javascript/blacklight/reports/table.vue
app/javascript/blacklight/search/searchControl.vue
app/javascript/packs/blacklight_vue.js
package.json
yarn.lock

Add a progress bar when searching.

---

solr/conf/solrconfig.xml

Ref https://github.com/sul-dlss/rialto/issues/316

Add autocommit to solrconfig.xml

---

app/controllers/catalog_controller.rb

Remove the abstract from the search results

---

Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb
app/models/solr_document.rb
app/search_builders/publication_search_builder.rb
spec/models/solr_document_spec.rb

Show a list of all of a persons publications on the person show page

---

app/controllers/catalog_controller.rb
app/models/solr_document.rb
spec/models/solr_document_spec.rb

Show grants on the publication page

---

app/javascript/blacklight/layouts/collaboration_report.vue
app/javascript/blacklight/layouts/research_trends_report.vue
app/javascript/blacklight/reports/yearSlider.vue
app/javascript/test/collaboration_report.spec.js
app/javascript/test/cross_disciplinary_report.spec.js
app/javascript/test/research_trends_report.spec.js
app/services/authors_coauthors_report_generator.rb
app/services/research_trends_report_generator.rb
spec/services/research_trends_report_generator_spec.rb

Filter the trend report by year

---

app/controllers/reports_controller.rb
app/services/authors_coauthor_countries_report_generator.rb
app/services/authors_coauthor_institutions_report_generator.rb
app/services/authors_coauthors_report_generator.rb
app/services/cross_disciplinary_report_generator.rb
app/services/report_generator.rb
app/services/research_trends_report_generator.rb
spec/requests/csv_reports_spec.rb

Permit parameters to avoid UnfilteredParameters error

---

app/controllers/catalog_controller.rb
app/helpers/application_helper.rb

refs https://github.com/sul-dlss/rialto-derivatives/issues/149

Make identifiers a list instead of single value.

---

app/models/solr_document.rb
app/search_builders/publication_search_builder.rb
spec/models/solr_document_spec.rb
spec/search_builders/publication_search_builder_spec.rb

For publication lists, sort by and display publication year.

---

app/services/research_trends_report_generator.rb
spec/services/research_trends_report_generator_spec.rb

Adds no concepts to research trends report.

---

app/services/authors_coauthors_report_generator.rb
spec/services/authors_coauthors_report_generator_spec.rb

Sorts co-author collaboration reports by descending collaboration count.

---

app/controllers/catalog_controller.rb
app/models/solr_document.rb
spec/models/solr_document_spec.rb

Only displays publication label when publications.

---

config/environments/production.rb

This reverts commit 86d8b6362ae694edf98f6c4bab548e6515c37415.

Revert "Force SSL use on production"

---

app/javascript/rialto/layouts/collaborationReport.vue

Switched order of map and table for collaborators by country.

---

app/javascript/rialto/choropleth.vue

Removes United States from chloropleth.

---

app/controllers/catalog_controller.rb
app/models/solr_document.rb
app/search_builders/grant_search_builder.rb
spec/models/solr_document_spec.rb
spec/search_builders/grant_search_builder_spec.rb

Links people to grants.

---

app/javascript/rialto/reports/table.vue
db/schema.rb

Displays message when reports returns no results.

---

app/javascript/rialto/layouts/collaborationReport.vue
app/javascript/test/rialto/collaboration_report.spec.js

Switched default collab report to by country.

---

app/javascript/blacklight/facet/value.vue

Fixes concept facets that include ampersands.

---

app/javascript/app.scss
app/javascript/blacklight/facet/item.vue
app/javascript/blacklight/facet/value.vue

Style facets for better usability.

---

app/javascript/rialto/layouts/collaborationReport.vue
app/javascript/rialto/layouts/crossDisciplinaryReport.vue
app/javascript/rialto/layouts/researchTrendsReport.vue

Adds report descriptions.

---

app/javascript/app.vue
app/javascript/packs/rialto.js
app/javascript/rialto/layouts/about.vue

Add an about page

---

app/controllers/catalog_controller.rb
app/javascript/rialto/layouts/crossDisciplinaryReport.vue

Relabel Concept as Topic area

---

app/javascript/blacklight/facet/item.vue
app/javascript/blacklight/facet/value.vue
app/javascript/test/blacklight/facet_item.spec.js
app/javascript/test/blacklight/facet_value.spec.js

Fixes #237 
Similar to this jQuery code in blacklight https://github.com/projectblacklight/blacklight/blob/master/app/javascript/blacklight/facet_load.js#L6-L18

Set an appropriate width for facet value

---

db/migrate/20181121152008_add_indexes.rb
db/schema.rb

Adds additional indexes.

---

.circleci/config.yml

Initial docker build from circle

---

app/javascript/app.vue
app/javascript/rialto/types.vue

Add type total counts to header/top nav

---

app/controllers/reports_controller.rb
app/javascript/rialto/layouts/collaborationReport.vue
app/javascript/rialto/reports/pagination.vue
app/javascript/rialto/reports/table.vue
app/services/authors_coauthor_institutions_report_generator.rb
app/services/authors_coauthors_report_generator.rb
app/services/report_generator.rb
spec/services/authors_coauthor_institutions_report_generator_spec.rb
spec/services/authors_coauthors_report_generator_spec.rb

Implements paging for coauthor report.

---

app/javascript/app.vue

Adds footer.

---

app/javascript/app.vue

Adds feedback link to nav bar.

---

app/javascript/app.vue

Moved location of beta.

---

app/controllers/catalog_controller.rb
app/javascript/rialto/layouts/about.vue
app/javascript/rialto/layouts/crossDisciplinaryReport.vue
app/javascript/rialto/layouts/home.vue
app/javascript/rialto/layouts/researchTrendsReport.vue

Refs sul-dlss/rialto-derivatives#164
Fixes #265
Fixes #266

Use consistent capitalization for Research Area

---

app/controllers/catalog_controller.rb

Changed number of results per page to 25.

---

app/javascript/rialto/layouts/collaborationReport.vue

Updates co-author collaboration help text.

---

app/services/research_trends_report_generator.rb
spec/services/research_trends_report_generator_spec.rb

Adds total row to research trends report.

---

app/services/authors_coauthor_countries_report_generator.rb
app/services/authors_coauthor_institutions_report_generator.rb
spec/services/authors_coauthor_countries_report_generator_spec.rb
spec/services/authors_coauthor_institutions_report_generator_spec.rb

Added unknown to coauthor country and institution reports.

---

config/webpack/environment.js

Removes sass loader

---

Gemfile
Gemfile.lock
app/javascript/test/setup.js
bin/webpack
bin/webpack-dev-server
package.json
yarn.lock

Fixes security error in webpack-dev-server

Upgrade webpacker

---

app/javascript/rialto/layouts/about.vue

Fixes #299 
Update about text.

Update about text in webapp related to grant data

---

Dockerfile-dev

Add BUNDLER_VERSION env to Dockerfile-dev

---

app/javascript/rialto/choropleth.vue
app/javascript/rialto/layouts/collaborationReport.vue

Switches to v-if for rendering choropleth.

---

app/services/research_trends_report_generator.rb
spec/services/research_trends_report_generator_spec.rb

Fixes TypeError in research_trends_report_generator.

---

Dockerfile-dev

Installs yarn in dev webapp.

---

app/javascript/rialto/reports/yearSlider.vue

Changes year slider to lazy.

---

app/controllers/catalog_controller.rb

Renamed university to institution for browse.

---

app/javascript/app.vue

Adds beta badge.

---

app/services/research_trends_report_generator.rb
spec/services/research_trends_report_generator_spec.rb

Fixes total row in research trends report.

---

.circleci/config.yml

Add upgrade bundler to circleci register image.

---

app/controllers/reports_controller.rb
app/javascript/rialto/layouts/collaborationReport.vue
app/javascript/rialto/reports/table.vue
app/services/authors_coauthor_countries_report_generator.rb
app/services/authors_coauthor_institutions_report_generator.rb
app/services/report_generator.rb
spec/services/authors_coauthor_countries_report_generator_spec.rb
spec/services/authors_coauthor_institutions_report_generator_spec.rb

Adds detail reports for coauthor country and coauthor institutions.

---

app/javascript/app.vue
app/javascript/blacklight/layouts/search.vue
app/javascript/packs/rialto.js
app/javascript/rialto/reports/table.vue
package.json
yarn.lock

Replaces progress bar.

---

app/javascript/rialto/choropleth.vue

Fixes filtering of USA from chloropleth.

---

app/services/authors_coauthor_countries_report_generator.rb
app/services/authors_coauthor_institutions_report_generator.rb
app/services/authors_coauthors_report_generator.rb
spec/requests/csv_reports_spec.rb
spec/services/authors_coauthor_countries_report_generator_spec.rb
spec/services/authors_coauthor_institutions_report_generator_spec.rb
spec/services/authors_coauthors_report_generator_spec.rb

just changing headers for the downloaded CSV, and in one case swapping column order

change labels of detail report downloads, and ordering in author-coauthor donwload

---

app/javascript/rialto/reports/table.vue

Better error handling when retrieving data fails.

---

app/javascript/rialto/layouts/about.vue
app/javascript/rialto/layouts/collaborationReport.vue

add some caveats to about and collab report

---

app/javascript/blacklight/layouts/showPage.vue
app/javascript/rialto/reports/table.vue

adjust text of error messages; fix typo

---

app/javascript/rialto/layouts/collaborationReport.vue
app/javascript/rialto/reports/table.vue

Clears report table and chloro when report changes.

---

app/javascript/rialto/layouts/collaborationReport.vue
app/javascript/rialto/layouts/researchTrendsReport.vue
app/javascript/test/rialto/collaboration_report.spec.js
app/javascript/test/rialto/research_trends_report.spec.js

Switched default year range to 3 years.

---

.circleci/config.yml

This should fix the master build.

Update master ruby version for build

---

.solr_wrapper.yml
Gemfile
Gemfile.lock
Rakefile

Drop solr_wrapper dependency

---

README.md

This will make it easier for anyone on the team to handle weekly dependency updates

Add deployment documentation

---

Dockerfile

This is causing the image to not startup properly in AWS.

Fix startup in Dockerfile

---

.circleci/config.yml
Dockerfile-dev
yarn.lock

Update to ruby 2.7.1

---

README.md

Update README to indicate versioning of rialto-webapp image
